# Generated by Django 5.1.14 on 2026-08-31 12:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('payroll', '0008_employer_pf_on_structure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_portal_submissions', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portal_submissions', to='clients.client')),
            ],
            options={
                'db_table': 'payroll_portal_submissions',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='PortalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('editor', 'Editor'), ('client_admin', 'Client Admin')], default='editor', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('must_change_password', models.BooleanField(default=True)),
                ('auth_token_hash', models.CharField(blank=True, default='', max_length=64)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_users', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_users_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll_portal_users',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='PortalSubmissionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(choices=[('NEW_EMPLOYEE', 'New employee'), ('REVISION', 'Salary revision'), ('EXIT', 'Exit / salary hold'), ('ADVANCE', 'Advance / loan'), ('ONE_TIME_EARNING', 'One-time earning'), ('ONE_TIME_DEDUCTION', 'One-time deduction'), ('NOTE', 'Note / instruction')], max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPLIED', 'Applied'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('sort', models.PositiveIntegerField(default=0)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payroll.portalsubmission')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_submission_items', to='payroll.portaluser')),
            ],
            options={
                'db_table': 'payroll_portal_submission_items',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.AddField(
            model_name='portalsubmission',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_submissions', to='payroll.portaluser'),
        ),
        migrations.AlterUniqueTogether(
            name='portalsubmission',
            unique_together={('client', 'month', 'year')},
        ),
    ]
