# Generated by Django 5.1.14 on 2026-09-01 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_portal_adjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portalsubmissionitem',
            name='item_type',
            field=models.CharField(choices=[('NEW_EMPLOYEE', 'New employee'), ('REVISION', 'Salary revision'), ('EXIT', 'Exit / resignation'), ('SALARY_HOLD', 'Salary hold'), ('ADVANCE', 'Advance / loan'), ('ONE_TIME_EARNING', 'One-time earning'), ('ONE_TIME_DEDUCTION', 'One-time deduction'), ('NOTE', 'Note / instruction')], max_length=30),
        ),
        migrations.CreateModel(
            name='PortalHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField(blank=True)),
                ('release_month', models.PositiveSmallIntegerField()),
                ('release_year', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_holds', to='payroll.employee')),
                ('hold_adjustment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_holds_held', to='payroll.onholdadjustment')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_holds', to='payroll.portalsubmissionitem')),
                ('release_adjustment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_holds_released', to='payroll.onholdadjustment')),
            ],
            options={
                'db_table': 'payroll_portal_holds',
                'ordering': ['release_year', 'release_month', 'id'],
            },
        ),
    ]
