# Generated by Django 5.1.14 on 2026-09-01 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_events(apps, schema_editor):
    """Give existing months a round history.

    PortalSubmission is unique per (client, month, year) and its status only
    holds the current state, so months that were already submitted/approved
    before this event log existed have no history rows. Reconstruct the
    latest round from the submission's own audit fields: one SUBMITTED event
    (if it was ever submitted) and one APPROVED event (if it was approved),
    using the original timestamps and actors.
    """
    PortalSubmission = apps.get_model("payroll", "PortalSubmission")
    PortalSubmissionEvent = apps.get_model("payroll", "PortalSubmissionEvent")

    for sub in PortalSubmission.objects.all().iterator():
        if sub.submitted_at:
            PortalSubmissionEvent.objects.create(
                submission_id=sub.id,
                event_type="SUBMITTED",
                item_count=sub.items.count(),
                actor_portal_id=sub.submitted_by_id,
                note="",
                created_at=sub.submitted_at,
            )
        if sub.approved_at:
            applied = sub.items.filter(status="APPLIED").count()
            PortalSubmissionEvent.objects.create(
                submission_id=sub.id,
                event_type="APPROVED",
                item_count=applied,
                actor_staff_id=sub.approved_by_id,
                note="",
                created_at=sub.approved_at,
            )


def remove_backfilled_events(apps, schema_editor):
    PortalSubmissionEvent = apps.get_model("payroll", "PortalSubmissionEvent")
    PortalSubmissionEvent.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_portal_hold'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalSubmissionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_portal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_events', to='payroll.portaluser')),
                ('actor_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_review_events', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='payroll.portalsubmission')),
            ],
            options={
                'db_table': 'payroll_portal_events',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.RunPython(backfill_events, remove_backfilled_events),
    ]
