# Generated by Django 5.1.14 on 2026-09-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0012_portal_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='payroll_is_active',
            field=models.BooleanField(default=False),
        ),
    ]
